title = 'Andrea Mandolo'
languageCode = 'en-us'

baseURL                          = "https://andrea.mandolo.net/"
theme                            = "introduction-minimal"
googleAnalytics                  = "G-RZBDVWV3MX"           # https://gohugo.io/templates/internal/#google-analytics

[params]
    themeStyle                   = "light"                 # Choose "light" or "dark" or "auto"
    favicon                      = "/img/fav.ico"          # Path to favicon file
    showRSSButton                = false                   # Show rss button in navigation
    fadeIn                       = true                    # Turn on/off the fade-in effect
    fadeInIndex                  = false                   # Turn on/off the fade-in effect on the index page even if fade-in was otherwise turned off
    dateFormat                   = "Jan 2, 2006"
    email                        = "andrea.mandolo@gmail.com"
    # customCSS                  = ["foo.css"]             # Include custom css files placed under assets/
    # customJS                   = ["foo.js"]              # Include custom JavaScript files placed under assets/
    # plausible                  = true                    # Use Plausible analytics (requires an account at Plausible.io)

    # Configure the home page
    [params.home]
        introHeight              = "fullheight"            # Input either "medium" or "large" or "fullheight"
        showLatest               = false                    # Show latest blog post summary
        showAllPosts             = false                   # Set true to list all posts on home page, or set false to link to separate blog list page
        allPostsArchiveFormat    = false                    # show all posts in an archive format
        numberOfProjectsToShow   = 0                       # Maximum number of projects to show on home page. Unset or comment out to show all projects
        localTime                = true                    # Show your current local time in contact section
        timeZone                 = "Europe/Rome"           # Your timezone as in the TZ* column of this list: https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        timeFormat               = "it-IT"                 # Language specific format to use
    [params.projects]
        useTwoColumns            = false                   # Use a layout with two columns instead of three

    # Share buttons on blog post pages
    [params.share]
        twitter                  = true
        facebook                 = true
        pinterest                = false

    # Social icons appear in introduction and contact section. Add as many more as you like.
    # Icon pack "fab" includes social network icons, see: https://fontawesome.com/icons?d=gallery&s=brands&m=free
    # Icon pack "fas" includes solid style icons, see: https://fontawesome.com/icons?d=gallery&s=solid&m=free
    [[params.social]]
        url   = "https://www.linkedin.com/in/andrea-mandolo/"
        icon  = "linkedin-in" # icon name without the 'fa-'
        icon_pack = "fab"
        html_attributes = 'target="_blank"'
    [[params.social]]
        url   = "https://github.com/amandolo"
        icon  = "github" # icon name without the 'fa-'
        icon_pack = "fab"
        html_attributes = 'target="_blank"'
    [[params.social]]
        url   = "https://twitter.com/andreamandolo"
        icon  = "twitter" # icon name without the 'fa-'
        icon_pack = "fab"
        html_attributes = 'target="_blank"'
    [[params.social]]
        url   = "https://www.facebook.com/andrea.mandolo/"
        icon  = "facebook-f" # icon name without the 'fa-'
        icon_pack = "fab"
        html_attributes = 'target="_blank"'
    [[params.social]]
        url   = "https://www.instagram.com/andrea.mandolo/"
        icon  = "instagram" # icon name without the 'fa-'
        icon_pack = "fab"
        html_attributes = 'target="_blank"'
    [[params.social]]
        url = "mailto:andrea.mandolo@gmail.com"  # For a direct email link, use "mailto:test@example.org".
        icon = "envelope" # icon name without the 'fa-'
        icon_pack = "fab fas"

    [params.resume]
        url = "resume.pdf"
        icon = "arrow-down" # icon name without the 'fa-'
        icon_pack = "fas"


# If you don't want to use the default menu, you can define one by yourself
# [[menu.main]]
#     name    = "Home"
#     url     = "/"
#     weight  = 0
# [[menu.main]]
#     name    = "Blog"
#     url     = "/blog/"
#     weight  = 1

# We only use tag as a taxonomies
# You can add more by yourself
[taxonomies]
  tag = "tags"
  series = "series"

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    # noClasses = true
    # For styles, see https://xyproto.github.io/splash/docs/longer/all.html
    style = "solarized-dark"
    tabWidth = 4

[languages]
    [languages.en]
        languageName     = "English"
        languageCode     = "en-us"
        contentDir       = "content/en"
        weight           = 0
        title            = "Andrea Mandolo"
        [languages.en.params]
            description  = "Andrea Mandolo - Senior DevOps Engineer"   # Max 160 characters show in search results
            footerText   = "*Built using [GitHub Actions](https://github.com/features/actions).*<br/>*Hosted on [GitHub Pages](https://pages.github.com/).*<br/>"