name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Generate resume
        run: export DOCKER_BUILDKIT=1 && make generate
        working-directory: ./resume

      - name: Generate site
        run: export DOCKER_BUILDKIT=1 && make generate
        working-directory: ./site

      - name: Group files
        run: mkdir -p public && cp -R ./resume/build/* ./public/ && cp -R ./site/public/* ./public/

      - name: Deploy on GitHub Pages branch
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: public
          folder: public